src/models/item.js
src/static/pdf-styles.css

1764 1755 1754

---

.ebignore
src/models/applet.js

Fix for https://github.com/ChildMindInstitute/mindlogger-backend/issues/1288

Fixed alerts

---

src/app.js
src/models/activity.js
src/models/applet.js
src/models/item.js

Fixes https://github.com/ChildMindInstitute/mindlogger-admin/issues/1743

Fix variables values

---

package-lock.json
package.json
src/models/activity.js
src/models/applet.js
src/utils.js
tests/models/activity.test.js
tests/utils.test.js

Fixes
ChildMindInstitute/mindlogger-app#2857
ChildMindInstitute/mindlogger-admin#1781
ChildMindInstitute/mindlogger-backend#1290

#1781 cast scores to float when testing visibility

---

src/models/activity.js

Page Breaks Between Each Activity in the Report#2859

add page break per activity

---

Jenkinsfile.groovy

Jenkins file for building the image has been added.

add jenkinsfile

---

env.example
src/app.ts
src/models/applet.ts

https://mindlogger.atlassian.net/browse/M2-3633

[M2-3633] fix: report filename

---

package-lock.json
package.json
src/pdf-utils.ts

PR to merge release/1.3.0 into `develop`

chore: sync release branch to the develop branch

---

src/db.ts
src/scripts/encryptLegacyPasswrd.ts

This script encrypt all plaintext password in sqllite database
To run it:
- Deploy new version of report server
- Go inside docker container  `docker exec -it <container id> /bin/sh`
- Run script:  `node dist/src/scripts/encryptLegacyPasswrd.js`

chore: Create script to encrypt all plaintext password (M2-8085)

---

src/models/activity.ts

Merge release/1.40 to dev to account for hotfixes merged directly to release branch

Release/v1.4.0 [dev]

---

src/models/item.ts

Merge `release/v1.5.1` to main

Release/v1.5.1 [main]

---

.github/workflows/ci.yaml
package.json
src/models/item.ts
src/scripts/encryptLegacyPasswrd.ts

The Report Server repo was missing PR CI GitHub actions. Adding them now.
Also fixed a two broken tests as well as some linting errors.
CI actions should all pass.

ci: Add standard PR CI checks

---

src/models/activity.ts

🔗 [Jira Ticket M2-8711](https://mindlogger.atlassian.net/browse/M2-8711)
This fixes a bug introduced by a minor refactoring done in #83, which was preventing **flagged scores** from being highlighted on the **Summary** page. The conditional logic object lookup should have been by `conditional.id` rather than `report.id`. This 1-liner fixes that.
| Before                      | After                                 |
| -------------------------------------- | ------------------------------------- |
| ![CleanShot 2025-02-18 at 13 36 28@2x](https://github.com/user-attachments/assets/e5f71c9a-62e3-4581-8434-32f81740b746) | ![CleanShot 2025-02-18 at 13 35 48@2x](https://github.com/user-attachments/assets/91452803-0f8f-45cf-a331-78f3a94eeac2) |
**These peer testing steps should pass regardless …

fix: Fix rendering flagged scores in summary (M2-8711)

---

src/encryption.ts
src/modules/report/helpers/decryptResponses.ts
src/modules/report/report.controller.ts

Changes include:
- Added Datadog metrics for:
- PDF generation
- Decryption
- Activity responses decryption

dd-metrics

---

package-lock.json
package.json
src/app.ts
src/core/services/LoggerService.ts
src/tracer.ts

Added more configuration to the Datadog tracer.  Added access logging for more observability

winston-middlware

---

src/app.ts
src/encryption.ts

Changes include:
- Changed a metric name to match others
- Added standard health check endpoints (mainly for filtering from logs)

chore: Metric name fix and health endpoints

---

.eslintrc.js
package-lock.json
package.json
src/core/helpers/ScoresCalculator.ts
src/core/helpers/getScoresSummary.test.ts
src/core/helpers/getScoresSummary.ts
src/core/helpers/isArray/index.ts
src/core/helpers/isFloat/index.ts
src/core/helpers/isNumber/index.ts
src/core/helpers/isObject/index.ts
src/core/helpers/isString/index.ts
src/core/interfaces/index.ts
src/models/activity.ts
src/models/applet.ts
src/models/item.ts
src/modules/report/helpers/conditionalLogic/ConditionalLogicService.test.ts
src/modules/report/helpers/conditionalLogic/ConditionalLogicService.ts
src/modules/report/report.controller.ts
src/pdf-utils.ts
tests/fixtures/activity.json
tests/models/activity.test.ts
tsconfig.json

Merge `release/2025.02.2` -> main

Release/2025.02.2 [main]

---

src/pdf-utils.ts

Release/2025.02.2 [dev]

---

Dockerfile
docker-entrypoint.sh
package-lock.json
package.json
src/tracer.ts

Changes include:
- Fixed startup variable for Datadog agent host configuration

Fixed Datadog tracing startup (M2-8788)

---

package-lock.json
package.json

🔗 [Jira Ticket M2-9075](https://mindlogger.atlassian.net/browse/M2-9075)
Changes include:
- Updating dependencies that have Critical or High findings.
- A full test of the report server should be done in dev

chore: Resolving vulnerabilities in dependencies
